// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/onboarding/ImmersiveDark.tsx": () => import("../components/mockups/onboarding/ImmersiveDark.tsx"),
  "./components/mockups/onboarding/MinimalPro.tsx": () => import("../components/mockups/onboarding/MinimalPro.tsx"),
  "./components/mockups/onboarding/SoftFriendly.tsx": () => import("../components/mockups/onboarding/SoftFriendly.tsx")
};
